ignoredBuiltDependencies:
  - esbuild
  - msw
  - protobufjs
  - unrs-resolver
overrides:
  js-cookie@<=3.0.5: '>=3.0.7'
  protobufjs@>=8.0.0 <8.2.0: '>=8.2.0'
  protobufjs@>=8.0.0 <=8.0.1: '>=8.0.2'
  uuid@<14.0.0: '>=14.0.0'
