apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-brukerdialog-frontend
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    app: dp-brukerdialog-frontend
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "64M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  image: "{{ image }}"
  port: 3000
  liveness:
    path: "/api/internal/isalive"
    initialDelay: 15
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: "/api/internal/isready"
    initialDelay: 15
    timeout: 1
  prometheus:
    path: "/api/internal/isready"
    enabled: true
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 512Mi
  env:
    - name: SELF_URL
      value: "{{ ingress }}"
    - name: DEKORATOR_URL
      value: "{{dekorator.url}}"
    - name: DEKORATOR_ENV
      value: "{{ dekorator.env }}"
    - name: APP_ENV
      value: "{{ app_env }}"
    - name: SANITY_DATASET
      value: "{{ sanity_dataset }}"
    - name: UNLEASH_SERVER_API_URL
      value: "{{ unleash.server_api_url }}"
    - name: FARO_URL
      value: "{{ faro_url }}"
    - name: DP_SOKNAD_ORKESTRATOR_URL
      value: "{{ dp_soknad_orkestrator_url }}"

  ingresses:
    {{#each ingresses as |url|}}
    - {{url}}
    {{/each}}
  accessPolicy:
    outbound:
      external:
        - host: rt6o382n.apicdn.sanity.io
        - host: www.nav.no
        - host: dekoratoren.dev.nav.no
        - host: dagpenger-unleash-api.nav.cloud.nais.io
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
        - application: dp-soknad-orkestrator
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      level: idporten-loa-high
  tokenx:
    enabled: true
