import countries from "i18n-iso-countries";
import englishLocale from "i18n-iso-countries/langs/en.json";
import bokmalLocale from "i18n-iso-countries/langs/nb.json";
import nynorskLocale from "i18n-iso-countries/langs/nn.json";

function setLocale(locale: string | undefined): string {
  switch (locale) {
    case "nb":
      countries.registerLocale(bokmalLocale);
      return "nb";
    case "nn":
      countries.registerLocale(nynorskLocale);
      return "nn";
    case "en":
      countries.registerLocale(englishLocale);
      return "en";

    default:
      countries.registerLocale(bokmalLocale);
      return "nb";
  }
}

export function finnLandnavnMedLocale(code: string, locale?: string) {
  return countries.getName(code, setLocale(locale)) || "nb";
}

export const LANDKODE_LISTE = [
  { value: "AFG" },
  { value: "ALA" },
  { value: "ALB" },
  { value: "DZA" },
  { value: "ASM" },
  { value: "AND" },
  { value: "AGO" },
  { value: "AIA" },
  { value: "ATA" },
  { value: "ATG" },
  { value: "ARG" },
  { value: "ARM" },
  { value: "ABW" },
  { value: "AUS" },
  { value: "AZE" },
  { value: "BHS" },
  { value: "BHR" },
  { value: "BGD" },
  { value: "BRB" },
  { value: "BLR" },
  { value: "BLZ" },
  { value: "BEN" },
  { value: "BMU" },
  { value: "BTN" },
  { value: "BOL" },
  { value: "BES" },
  { value: "BIH" },
  { value: "BWA" },
  { value: "BVT" },
  { value: "BRA" },
  { value: "IOT" },
  { value: "BRN" },
  { value: "BFA" },
  { value: "BDI" },
  { value: "KHM" },
  { value: "CMR" },
  { value: "CAN" },
  { value: "CPV" },
  { value: "CYM" },
  { value: "CAF" },
  { value: "TCD" },
  { value: "CHL" },
  { value: "CHN" },
  { value: "CXR" },
  { value: "CCK" },
  { value: "COL" },
  { value: "COM" },
  { value: "COG" },
  { value: "COD" },
  { value: "COK" },
  { value: "CRI" },
  { value: "CIV" },
  { value: "CUB" },
  { value: "CUW" },
  { value: "DJI" },
  { value: "DMA" },
  { value: "DOM" },
  { value: "ECU" },
  { value: "EGY" },
  { value: "SLV" },
  { value: "GNQ" },
  { value: "ERI" },
  { value: "ETH" },
  { value: "FLK" },
  { value: "FRO" },
  { value: "FJI" },
  { value: "GUF" },
  { value: "PYF" },
  { value: "ATF" },
  { value: "GAB" },
  { value: "GMB" },
  { value: "GEO" },
  { value: "GHA" },
  { value: "GIB" },
  { value: "GRL" },
  { value: "GRD" },
  { value: "GLP" },
  { value: "GUM" },
  { value: "GTM" },
  { value: "GGY" },
  { value: "GIN" },
  { value: "GNB" },
  { value: "GUY" },
  { value: "HTI" },
  { value: "HMD" },
  { value: "VAT" },
  { value: "HND" },
  { value: "HKG" },
  { value: "IND" },
  { value: "IDN" },
  { value: "IRN" },
  { value: "IRQ" },
  { value: "ISR" },
  { value: "JAM" },
  { value: "JPN" },
  { value: "JOR" },
  { value: "KAZ" },
  { value: "KEN" },
  { value: "KIR" },
  { value: "PRK" },
  { value: "KOR" },
  { value: "KWT" },
  { value: "KGZ" },
  { value: "LAO" },
  { value: "LBN" },
  { value: "LSO" },
  { value: "LBR" },
  { value: "LBY" },
  { value: "MAC" },
  { value: "MKD" },
  { value: "MDG" },
  { value: "MWI" },
  { value: "MYS" },
  { value: "MDV" },
  { value: "MLI" },
  { value: "MHL" },
  { value: "MTQ" },
  { value: "MRT" },
  { value: "MUS" },
  { value: "MYT" },
  { value: "MEX" },
  { value: "FSM" },
  { value: "MAR" },
  { value: "MDA" },
  { value: "MCO" },
  { value: "MNG" },
  { value: "MNE" },
  { value: "MSR" },
  { value: "MOZ" },
  { value: "MMR" },
  { value: "NAM" },
  { value: "NRU" },
  { value: "NPL" },
  { value: "NCL" },
  { value: "NZL" },
  { value: "NIC" },
  { value: "NER" },
  { value: "NGA" },
  { value: "NIU" },
  { value: "NFK" },
  { value: "MNP" },
  { value: "OMN" },
  { value: "PAK" },
  { value: "PLW" },
  { value: "PSE" },
  { value: "PAN" },
  { value: "PNG" },
  { value: "PRY" },
  { value: "PER" },
  { value: "PHL" },
  { value: "PCN" },
  { value: "PRI" },
  { value: "QAT" },
  { value: "REU" },
  { value: "RUS" },
  { value: "RWA" },
  { value: "BLM" },
  { value: "SHN" },
  { value: "KNA" },
  { value: "LCA" },
  { value: "MAF" },
  { value: "SPM" },
  { value: "VCT" },
  { value: "WSM" },
  { value: "SMR" },
  { value: "STP" },
  { value: "SAU" },
  { value: "SEN" },
  { value: "SRB" },
  { value: "SYC" },
  { value: "SLE" },
  { value: "SGP" },
  { value: "SXM" },
  { value: "SLB" },
  { value: "SOM" },
  { value: "ZAF" },
  { value: "SGS" },
  { value: "SSD" },
  { value: "LKA" },
  { value: "SDN" },
  { value: "SUR" },
  { value: "SWZ" },
  { value: "SYR" },
  { value: "TWN" },
  { value: "TJK" },
  { value: "TZA" },
  { value: "THA" },
  { value: "TLS" },
  { value: "TGO" },
  { value: "TKL" },
  { value: "TON" },
  { value: "TTO" },
  { value: "TUN" },
  { value: "TUR" },
  { value: "TKM" },
  { value: "TCA" },
  { value: "TUV" },
  { value: "UGA" },
  { value: "UKR" },
  { value: "ARE" },
  { value: "USA" },
  { value: "UMI" },
  { value: "URY" },
  { value: "UZB" },
  { value: "VUT" },
  { value: "VEN" },
  { value: "VNM" },
  { value: "VGB" },
  { value: "VIR" },
  { value: "WLF" },
  { value: "ESH" },
  { value: "YEM" },
  { value: "ZMB" },
  { value: "ZWE" },
  { value: "BEL" },
  { value: "BGR" },
  { value: "DNK" },
  { value: "EST" },
  { value: "FIN" },
  { value: "FRA" },
  { value: "GRC" },
  { value: "IRL" },
  { value: "ISL" },
  { value: "ITA" },
  { value: "HRV" },
  { value: "CYP" },
  { value: "LVA" },
  { value: "LIE" },
  { value: "LTU" },
  { value: "LUX" },
  { value: "MLT" },
  { value: "NLD" },
  { value: "POL" },
  { value: "PRT" },
  { value: "ROU" },
  { value: "SVK" },
  { value: "SVN" },
  { value: "ESP" },
  { value: "CHE" },
  { value: "SWE" },
  { value: "CZE" },
  { value: "DEU" },
  { value: "HUN" },
  { value: "AUT" },
  { value: "NOR" },
  { value: "SJM" },
  { value: "GBR" },
  { value: "JEY" },
  { value: "IMN" },
];

export const LANDLISTE = LANDKODE_LISTE.map((land) => ({
  value: land.value,
  label: finnLandnavnMedLocale(land.value),
}));
